database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: Abc_123456
  database: goauth
  maxidleconns: 5
  maxopenconns: 5
oauth:
  accesstokenlifetime: 3600
  refreshtokenlifetime: 1209600
  authcodelifetime: 3600
session:
  secret: test_secret
  path: /
  maxage: 604800
  httponly: True
serverport: 8080
isdevelopment: True